# Generated by Django 5.2.4 on 2025-07-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='last_swiped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedword',
            name='swipe_right_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
