# Generated by Django 5.2.4 on 2025-07-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnwords', '0002_savedword_last_swiped_at_savedword_next_review_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedword',
            old_name='last_swiped_at',
            new_name='last_reviewed_at',
        ),
        migrations.RenameField(
            model_name='savedword',
            old_name='swipe_right_count',
            new_name='remembered_count',
        ),
    ]
