# Generated by Django 5.2.4 on 2025-08-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnwords', '0003_rename_last_swiped_at_savedword_last_reviewed_at_and_more'),
    ]

    operations = [
    ]
